// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DIIS.PersonApp.EntitiesLINQ
{
    [Table("CATEGORIES")]
    public partial class Categories
    {
        public Categories()
        {
            Products = new HashSet<Products>();
        }

        [Key]
        [Column("CATEGORY_ID")]
        [Precision(9)]
        public int CategoryId { get; set; }
        [Required]
        [Column("CATEGORY_NAME")]
        [StringLength(15)]
        [Unicode(false)]
        public string CategoryName { get; set; }
        [Column("DESCRIPTION")]
        [StringLength(2000)]
        [Unicode(false)]
        public string Description { get; set; }
        [Column("PICTURE")]
        [StringLength(255)]
        [Unicode(false)]
        public string Picture { get; set; }

        [InverseProperty("Category")]
        public virtual ICollection<Products> Products { get; set; }
    }
}