// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DIIS.PersonApp.EntitiesLINQ
{
    [Table("FISH")]
    public partial class Fish
    {
        [Key]
        [Column("ID")]
        [StringLength(2)]
        [Unicode(false)]
        public string Id { get; set; }
        [Required]
        [Column("NAME")]
        [StringLength(100)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("PRICE_UNIT", TypeName = "NUMBER(16,2)")]
        public decimal? PriceUnit { get; set; }
        [Column("EXPIRED_DATE", TypeName = "DATE")]
        public DateTime? ExpiredDate { get; set; }
    }
}