// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DIIS.PersonApp.EntitiesLINQ
{
    [Table("SUPPLIERS")]
    [Index("CompanyName", Name = "IDX_SUPPLIERS_COMPANY_NAME")]
    [Index("PostalCode", Name = "IDX_SUPPLIERS_POSTAL_CODE")]
    public partial class Suppliers
    {
        public Suppliers()
        {
            Products = new HashSet<Products>();
        }

        [Key]
        [Column("SUPPLIER_ID")]
        [Precision(9)]
        public int SupplierId { get; set; }
        [Required]
        [Column("COMPANY_NAME")]
        [StringLength(40)]
        [Unicode(false)]
        public string CompanyName { get; set; }
        [Column("CONTACT_NAME")]
        [StringLength(30)]
        [Unicode(false)]
        public string ContactName { get; set; }
        [Column("CONTACT_TITLE")]
        [StringLength(30)]
        [Unicode(false)]
        public string ContactTitle { get; set; }
        [Column("ADDRESS")]
        [StringLength(60)]
        [Unicode(false)]
        public string Address { get; set; }
        [Column("CITY")]
        [StringLength(15)]
        [Unicode(false)]
        public string City { get; set; }
        [Column("REGION")]
        [StringLength(15)]
        [Unicode(false)]
        public string Region { get; set; }
        [Column("POSTAL_CODE")]
        [StringLength(10)]
        [Unicode(false)]
        public string PostalCode { get; set; }
        [Column("COUNTRY")]
        [StringLength(15)]
        [Unicode(false)]
        public string Country { get; set; }
        [Column("PHONE")]
        [StringLength(24)]
        [Unicode(false)]
        public string Phone { get; set; }
        [Column("FAX")]
        [StringLength(24)]
        [Unicode(false)]
        public string Fax { get; set; }
        [Column("HOME_PAGE")]
        [StringLength(500)]
        [Unicode(false)]
        public string HomePage { get; set; }

        [InverseProperty("Supplier")]
        public virtual ICollection<Products> Products { get; set; }
    }
}